# JetStream cluster member (Windows paths)
server_name: nats-1
port: 4222
http: 8222

jetstream {
	store_dir: C:/data
}

cluster {
	name: demo-smtp
	listen: 0.0.0.0:6222
	advertise: nats-1:6222
	routes: [
		nats://nats-1:6222
		nats://nats-2:6222
		nats://nats-3:6222
	]
}
